{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.slurmKey.create (not .Values.accounting.external) (not .Values.controller.external) }}
{{- /* https://github.com/helm/helm-www/issues/1259 */}}
{{- $secretName := include "slurm.authSlurmRef.name" . -}}
{{- $secret := lookup "v1" "Secret" (include "slurm.namespace" .) $secretName -}}
{{- $key := (include "slurm.authSlurmRef.key" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "slurm.namespace" . }}
  {{- with .Values.slurmKey.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with .Values.slurmKey.annotations */}}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $secret }}
  {{- $secretData := (get $secret "data") }}
  {{ $key }}: {{ get $secretData $key }}
  {{- else }}{{- /* if $secret */}}
  {{ $key }}: {{ randAscii 1024 | b64enc }}
  {{- end }}{{- /* if $secret */}}
immutable: true
{{- end }}{{- /* if and .Values.slurmKey.create (not .Values.accounting.external) (not .Values.controller.external) */}}
