rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - nodes
      - pods/binding
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - patch
      - update
  - apiGroups:
      - slinky.slurm.net
    resources:
      - accountings
      - controllers
      - loginsets
      - nodesets
      - restapis
      - tokens
    verbs:
      - create
      - delete
      - update
